### PR TITLE
Update login.tsx

### PR DESCRIPTION
**Pull request by manipinnaka1125**
The code was refined with several enhancements to elevate its quality, maintainability, and user interface experience. Legacy imports were replaced with modern ones, adhering to current best practices. Redundant theme calls were consolidated, optimizing code readability and resource usage. Object destructuring improved readability by simplifying state property extraction from Redux. Styling was streamlined by removing unnecessary spread operators and type definitions, enhancing code structure. Layout responsiveness was optimized using flexbox and responsive design techniques, ensuring consistent user experience across various devices. Redundant comments and type annotations were removed, making the codebase more concise and understandable. Event handling for link components was refactored for clarity, while unnecessary wrapper components were minimized, simplifying JSX structure. Component names were refined to better convey their purpose and usage within the parent component, contributing to improved readability and maintainability. These refinements collectively aim to enhance the codebase's overall quality and user interface, ensuring a more streamlined and engaging experience for users.

### CODE REVIEW

**Comment by eleanorreem** [comment]
Thank you so much for your contribution. It is hugely helpful. I deployed your changes to Vercel and unfortunately they caused issues with styling.

Screenshot 2024-05-06 at 16 51 03

I would recommend splitting out the changes into smaller pull requests as there were a lot of changes at once which touched different issues. Thanks again ⭐

**Comment by manipinnaka1125** [comment]
Can I have another try for it

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by manipinnaka1125** [comment]
Can I have any opportunity to work with you I love contributing things ❤️ can I have any chance to me I run and clone the things properly and also code for it

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by kyleecodes** [comment]
Hey @manipinnaka1125, thank you for your contribution!
As per our [Contributor Guidelines](https://github.com/chaynHQ/bloom-frontend/blob/develop/CONTRIBUTING.md), to accept your PR you must create or claim an issue to describe your changes. This helps us keep track and document open-source contributions. Please create an issue or claim the issue for this PR if it already exists. Thanks again!

**Pull request closed without merging**
