### PR TITLE
International Leave this site options 

### PR DESCRIPTION
**Pull request by anmol-fzr**
### Issue :
Issue number: 888
Issue link: https://github.com/chaynHQ/bloom-frontend/issues/888

### What changes did you make?
Added International to Leave this site options, now wikipedia and google links open respective to user's current language

### Why did you make the changes?
This feature was obvious to have and also had an issue on the repo

### Did you run tests?
I ran tests

### CODE REVIEW

**Comment by eleanorreem** [comment]
Hi @anmol-fzr, this looks great from an initial look. As per our [Contributor Guidelines](https://github.com/chaynHQ/bloom-frontend/blob/develop/CONTRIBUTING.md), to accept your PR, you need to claim an issue. I can't seem to tag you without you commenting on the issue. This helps us keep track and document open-source contributions. 😄  Can you comment on  the issue and then I can properly reviewand authorise the workflow 🎉

**Comment by anmol-fzr** [comment]
@eleanorreem  Hopefully this PR is ready to be merged. Merge this if possible if not please inform so that i can make suitable changes

**Comment by eleanorreem** [comment]
Hey @anmol-fzr, this PR is failing to build unfortunately. The error I get looks like the screen shot below. Running `yarn build` and running the `yarn lint`  will ensure you don't encounter these errors. The error comes from the use of double quotes where single should be used. Let me know if you have any questions. Thanks!
Screenshot 2024-05-11 at 17 00 48

**Comment by anmol-fzr** [comment]
@eleanorreem I have fixed the Linting Error you mentioned while building this project i also encountered error about "@mui/system" library i didn't changed any other file as this library is used in the code on the official repo, assuming this won't cause errors on build.

**Comment by eleanorreem** [comment]
Thanks for this!

**Pull request merged**
