### PR TITLE
added robots.txt file with disallowed urls. 

### PR DESCRIPTION
**Pull request by DustyDogCodex**
Solves issue #610 .

Also added a sitemap.xml.tsx file and linked it to robots.txt. Please let me know if you want me to edit/remove the sitemap file.

### CODE REVIEW

**Comment by DustyDogCodex** [comment]
Hi! 
Is there a function/api call to get all the urls from dynamically generated routes like /courses/[slug]/[sessionSlug] route and /welcome/[partnerName]?

**Comment by kyleecodes** [comment]
Hey @DustyDogCodex just saw your question, thanks for your patience!

Great question! Yes, in Bloom we use Next.js, which uses the `getStaticPaths` function to generate dynamic routes for pages. This function allows you to specify the paths that should be pre-rendered at build time. 

You can refer to the Next.js documentation for more info on [dynamic routes](https://nextjs.org/docs/routing/dynamic-routes).

Does this help? Anything in particular you're interested in doing with dynamic routes for Bloom?

**Comment by kyleecodes** [comment]
> Hi @kyleecodes !
> 
> Thanks for getting back to me! I asked about dynamic routes as they would be need to be added to the sitemap and robots.txt as they are created and updated. This can be done dynamically in the robots.txt using the `getStaticPaths` functions. However, I looked at the project again and it looks like the courses path will be hidden behind user login/authentication so I don't think it'll even be available to any web crawlers to peruse through. If you'd like I can change the sitemap to a manual one which omits the /courses dynamic routes.

Interesting! Just so I'm clear, you want to set-up dynamic route generation in `robots.txt` and `sitemap.xml.tsx` so that new and updated routes will not need to be manually updated, but because /courses are hidden behind user/authentication, you'll change the sitemap to manually omit the /course routes?

Thanks again for your interest!

**Comment by DustyDogCodex** [comment]
Hi @kyleecodes ,

Yea that's more or less it! 

So currently I have static routes manually entered in the sitemap and some code for representing the dynamic routes under /courses. As the /courses routes are being login access, web crawlers cannot access them UNLESS the web crawlers use some specialized package/code to use login credentials and view /courses. Here we have two options: 

1) If you want the /courses routes to not be accessible to web crawlers, I can add them to the disallow list in robots.txt! 

2) If you do want the /courses routes to be accessible to web crawlers, I can figure out how to get dynamic route paths from getStaticProps and replace my current code for adding these routes to the sitemap. From my understanding, if I implement this correctly, everytime a new course is added, the sitemap would automatically be updated with the route for that course withoute needing manual editing of the sitemap.

Alternatively, if you would like the /course route to be protected from web crawlers yet still have some data on courses available for SEO, I can create a new route for just displaying some course info on the frontend. That way you can choose what gets displayed and this route will be a static route that doesn't need to be updated, nor is it behind login access. This route would be like a sneak peek or a welcome brochure to the courses without showing everything in them if that makes sense? Just something for the web crawlers to look at and know what the website's about and what it's offering.

Please let me know what you think and I will be happy to work on this :)

**Comment by kyleecodes** [comment]
@DustyDogCodex Looks good to me!

To get started, can you create a new issue for this where we can track progress and tag Chayn's engineers for review on what to do with web crawler routes in /courses? You can copy what you've written here to the issue, and add any additional links to resources if you have them. Meanwhile you can get started with dynamic route generation in `robot.txt` / XML sitemap.

**Pull request merged**
