### PR TITLE
Fix: error message changed when code has been already applied

### PR DESCRIPTION
**Pull request by nahuelDev23**
### Issue link / number:
816
### What changes did you make?
I have changed the error messages for the ApplyCodeForm.tsx component, both for English and Spanish languages.
### Why did you make the changes?
Because it was a requirement.
<!--- PR CHECKLIST: PLEASE REMOVE BEFORE SUBMITTING —>
Before submitting, check that you have completed the following tasks:
- [ ] Answered the questions above.
- [ ] Read Chayn's Contributing Guidelines in the CONTRIBUTING.md file.
- [ ] Enabled "Allow edits and access to secrets by maintainers" on this PR.
- [ ] If applicable, include images in the description.
After submitting, please be available for discussion. Thank you!

### CODE REVIEW

**Comment by nahuelDev23** [comment]
@eleanorreem

**Comment by kyleecodes** [comment]
Hi @nahuelDev23, thank you for your PR.
May you comment [on the issue ](https://github.com/chaynHQ/bloom-frontend/issues/816)so I can assign it to you? This helps us keep track of contributions.
I've also tagged a reviewer for your PR.

**Review by annarhughes — COMMENTED** [review]
Thanks for this contribution Nahuel 🌟 Looks almost good to go, it would be great to add placeholder strings for the other 4 languages, so it doesn't error in that language. We can use the english string for now!

Looks like some rouge `package-lock.json` and `yarn.lock` changes snook in. Could we undo those as they may cause clashes!

**Comment by kyleecodes** [comment]
Hey @nahuelDev23 👋

Pinging you again to see if you're still interested in completing your contribution?
To merge your PR, please refer to the comments above so we can get you assigned to the correct issue and remove the lockfiles.
Once those are completed we can move forward. 🙏

**Pull request closed without merging**
