### PR TITLE
Add Spanish Create User Test

### PR DESCRIPTION
**Pull request by cmstrandwold**
### What changes did you make?

- Added new create user test in Spanish based on the existing test in German. 
- Added new Cypres command to visit Spanish page (visitSpanishPage)

### Why did you make the changes?

Changes were made as per instructions in the issue.

### CODE REVIEW

**Comment by cmstrandwold** [comment]
Hi @eleanorreem, looking for a review on this PR. Please let me know if there is any other information I should add or change, thanks!

**Comment by eleanorreem** [comment]
Brilliant - thank you. I have approved and will deploy when the workflows have run ⭐

**Review by eleanorreem — APPROVED** [review]

**Comment by kyleecodes** [comment]
@cmstrandwold you are merged! 🎉

Thank you for your patience as we worked out our workflows.

**Comment by cmstrandwold** [comment]
Thanks!!

**Pull request merged**
