### PR TITLE
Fix to Bloom Open Graph Metadata preview

### PR DESCRIPTION
**Pull request by anmol-fzr**
### What changes did you make?
Fixed the OpenGraphmetadata component to get meta tags in the DOM

### CODE REVIEW

**Comment by eleanorreem** [comment]
Hi @anmol-fzr , Thanks for your contribution! Did you have a screen shot to show this worked? Thanks!

**Comment by eleanorreem** [comment]
Screenshot 2024-06-19 at 16 05 49 

Hi @anmol-fzr , Thanks for your work. It's finally loading the text which is great. I deployed your branch but I don't think the image is rendering. Could you have a quick look and see if you can debug!

**Comment by anmol-fzr** [comment]
@eleanorreem  

You can use this chrome extension to check [Social Share Preview](https://chromewebstore.google.com/detail/social-share-preview/ggnikicjfklimmffbkhknndafpdlabib)

Screenshot-2024-06-19_20-43-10

**Comment by eleanorreem** [comment]
Okay brilliant. Thanks @anmol-fzr. Thats a great tip!

**Comment by anmol-fzr** [comment]
@kyleecodes Fixed the aspect-ratio issue for the og:image meta tag at PR https://github.com/chaynHQ/bloom-frontend/pull/998

**Pull request merged**
