### PR TITLE
App router migration new relic configuration

### PR DESCRIPTION
**Pull request by boodland**
Children PR for the progressive migration of _app.tsx and _document.tsx within the Root Layout

Issue link / number:
#1083

What changes did you make?
Created new relic configuration
Added new relic configuration to root layout

Why did you make the changes?
In order to be able to have new relic within app router

Did you run tests?
Yes

Navigate to http://localhost:3000/public-route-test to check that the head nr-browser-agent and body scripts are added properly

image

### CODE REVIEW

**Comment by boodland** [comment]
@annarhughes This PR needs to point to app-router-migration branch once #1085 is merged

**Comment by boodland** [comment]
@eleanorreem, @annarhughes I have just changed the base branch, have a look when possible. Thanks

**Comment by eleanorreem** [comment]
Merged @boodland sorry for the delay.

**Comment by boodland** [comment]
> Merged @boodland sorry for the delay.

No worries at all, very happy to help

**Pull request merged**
